From f4f7931b1c3f513baa2e38b5ef524dc50a4e0298 Mon Sep 17 00:00:00 2001
From: Brian Dolbec <dolsen@gentoo.org>
Date: Thu, 23 Apr 2020 10:24:52 -0700
Subject: [PATCH 1/4] all_pythons.py: Update python versions

---
 scripts/all_pythons.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/scripts/all_pythons.sh b/scripts/all_pythons.sh
index fe1d74f..3c85974 100755
--- a/scripts/all_pythons.sh
+++ b/scripts/all_pythons.sh
@@ -2,7 +2,7 @@
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-for VER in 2.7 3.3 3.4 3.5
+for VER in 2.7 3.6 3.7 3.8
 do
     echo
     echo "testing python${VER}"

From 668da642eb0a9696e8cd8ba918bfd8595989028d Mon Sep 17 00:00:00 2001
From: Brian Dolbec <dolsen@gentoo.org>
Date: Thu, 23 Apr 2020 10:28:31 -0700
Subject: [PATCH 2/4] tests/server.py: Add time.sleep() delay after shutdown

This is to help prevent a possible threading lock error if
traceback errors are raised.
I was experiencing this fault while debugging python 3.7 and 3.8 test
errors.  It prevented the sys.exit() at the end of the tests.
---
 tests/server.py | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/tests/server.py b/tests/server.py
index 51d49b7..6a32a2d 100644
--- a/tests/server.py
+++ b/tests/server.py
@@ -13,6 +13,7 @@
 
 import os
 import threading
+import time
 
 from g_sorcery.compatibility import py2k
 
@@ -49,3 +50,4 @@ def run(self):
 
     def shutdown(self):
         self.httpd.shutdown()
+        time.sleep(0.5)

From 0a1e95f99446dadcbce47f6d404ad8adba65e747 Mon Sep 17 00:00:00 2001
From: Brian Dolbec <dolsen@gentoo.org>
Date: Thu, 23 Apr 2020 10:35:30 -0700
Subject: [PATCH 3/4] test_DBGenerator.py, test_PackageDB.py: Fix test errors

The http server was not being shutdown when exceptions were raised
This caused other errors in tests run after the failed test.
---
 tests/test_DBGenerator.py | 12 +++++++-----
 tests/test_PackageDB.py   | 12 +++++++-----
 2 files changed, 14 insertions(+), 10 deletions(-)

diff --git a/tests/test_DBGenerator.py b/tests/test_DBGenerator.py
index 9a47c86..3c28278 100644
--- a/tests/test_DBGenerator.py
+++ b/tests/test_DBGenerator.py
@@ -4,9 +4,9 @@
 """
     test_DBGenerator.py
     ~~~~~~~~~~~~~~~~~~~
-    
+
     DBGenerator test suite
-    
+
     :copyright: (c) 2013 by Jauhien Piatlicki
     :license: GPL-2, see LICENSE for more details.
 """
@@ -81,11 +81,13 @@ def test_functionality(self):
         srv = Server(orig_tempdir.name)
         srv.start()
 
-        pkg_db = db_generator(self.tempdir.name, "test_repo",
+        try:
+            pkg_db = db_generator(self.tempdir.name, "test_repo",
                               common_config = common_config, config = config)
 
-        srv.shutdown()
-        srv.join()
+        finally:
+            srv.shutdown()
+            srv.join()
 
         self.assertEqual(set(pkg_db.list_categories()), set(["app-test1", "app-test2"]))
         self.assertTrue(pkg_db.in_category("app-test1", "test"))
diff --git a/tests/test_PackageDB.py b/tests/test_PackageDB.py
index 152c605..8be8f8a 100644
--- a/tests/test_PackageDB.py
+++ b/tests/test_PackageDB.py
@@ -70,11 +70,13 @@ def test_functionality(self):
 
             srv = Server(orig_tempdir.name, port=port)
             srv.start()
-            self.assertRaises(IntegrityError, test_db.sync, sync_address)
-            os.system("cd " + orig_tempdir.name + " && mv good.tar.gz dummy.tar.gz")
-            test_db.sync(sync_address)
-            srv.shutdown()
-            srv.join()
+            try:
+                self.assertRaises(IntegrityError, test_db.sync, sync_address)
+                os.system("cd " + orig_tempdir.name + " && mv good.tar.gz dummy.tar.gz")
+                test_db.sync(sync_address)
+            finally:
+                srv.shutdown()
+                srv.join()
             test_db.read()
             self.assertEqual(orig_db.database, test_db.database)
             self.assertEqual(orig_db.get_common_data("app-test1"), test_db.get_common_data("app-test1"))

From 881824e00213dcaddc2f457dee3f57e597ebb653 Mon Sep 17 00:00:00 2001
From: Brian Dolbec <dolsen@gentoo.org>
Date: Thu, 23 Apr 2020 10:39:09 -0700
Subject: [PATCH 4/4] tests/server/py: Fix an inheritence error in py 3.7, 3.8

self.directory was being overridden by the super class instance.
Rename this local variable to prevent it being overridden.
---
 tests/server.py | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/tests/server.py b/tests/server.py
index 6a32a2d..aa895ea 100644
--- a/tests/server.py
+++ b/tests/server.py
@@ -4,9 +4,9 @@
 """
     server.py
     ~~~~~~~~~
-    
+
     test server
-    
+
     :copyright: (c) 2013 by Jauhien Piatlicki
     :license: GPL-2, see LICENSE for more details.
 """
@@ -18,7 +18,7 @@
 from g_sorcery.compatibility import py2k
 
 if py2k:
-    from SocketServer import TCPServer as HTTPServer 
+    from SocketServer import TCPServer as HTTPServer
     from SimpleHTTPServer import SimpleHTTPRequestHandler
 else:
     from http.server import HTTPServer
@@ -27,24 +27,24 @@
 def HTTPRequestHandlerGenerator(direct):
 
     class HTTPRequestHandler(SimpleHTTPRequestHandler, object):
-        directory = direct
 
         def __init__(self, request, client_address, server):
+            self.direct = direct
             super(HTTPRequestHandler, self).__init__(request, client_address, server)
 
         def translate_path(self, path):
-            return os.path.join(self.directory, path[1:])
+            return os.path.join(self.direct, path[1:])
 
     return HTTPRequestHandler
 
-    
+
 class Server(threading.Thread):
     def __init__(self, directory, port=8080):
         super(Server, self).__init__()
         HTTPServer.allow_reuse_address = True
         server_address = ('127.0.0.1', port)
         self.httpd = HTTPServer(server_address, HTTPRequestHandlerGenerator(directory))
-    
+
     def run(self):
         self.httpd.serve_forever()
 
